### ISSUE TITLE
Feature suggestion - Add callback for stdout and stderr processing

### ISSUE THREAD

**Issue by cessna048** [jamesmanning/RunProcessAsTask#10]
This would allow use of the the class with programs that send progress reports via stderr (or stdout) such as mkisofs

**Comment by jamesmanning** [comment]
Thanks for the suggestion, @cessna048 !

At the moment, I think of that as out of scope, and this library is more for callers that don't need to interact with the running process, just need results when it's done. If you want to interact with the running process, the existing events off of Process that deliver lines on stdout and stderr are the way to go, IMHO.

**Comment by isolatedperson** [comment]
I think i have a similar request, i want to interact with already started process and communicate with it like Expect CLI Automation tool

**Comment by jamesmanning** [comment]
@isolatedperson IMHO, that'd be similar to the previous request in falling out of scope for this little project.  As written, this wrapper needs to be the one to start a process since it's going to tell the process to raise stdout/stderr data events and then to hook up handlers to capture the lines written with them.  If the process has already started, it's too late to tell the process to emit those events, and even if the process is already doing so, if the process is already running it's too late to hook up the handlers to ensure we're capturing (all of) the contents of both stdout/stderr.

This wrapper is really just about simplifying the scenario of just running the process and getting the results when it's done - if you want something more interactive and similar to the 'expect' command, you might consider https://github.com/wiwanek/Expect.NET/ available from https://www.nuget.org/packages/Expect.NET/ which seems a much better fit look at examples of how it can react like https://github.com/wiwanek/Expect.NET/wiki/how-to-react-to-session's-output
