### ISSUE TITLE
Get StandardOutput as its written..

### ISSUE THREAD

**Issue by dazinator** [jamesmanning/RunProcessAsTask#17]
Thanks for a useful library.

When using `Process` directly, you can handle events `Process.OutputDataReceived` and `ErrorDataReceived` in order to receive the output whilst the process is still running, before it has exited.

Is there any way to achieve this with `RunProcessAsTask` ? for example, the process writes some standard output to indicate progress, and I'd like to be intercepting this whilst its running, so I can be updating a [progress indiactor](https://github.com/Mpdreamz/shellprogressbar)

**Comment by jamesmanning** [comment]
@dazinator RunProcessAsTask is very much intended for the use case of starting a process and then getting the results (exit code, stdout, stderr, runtime, etc) after it's finished running, nothing about interacting with it while it's still running.  I like the idea of having a progress bar, but I think you're better off just using Process directly and the events you mentioned.

**Comment by dazinator** [comment]
Ok thanks for the response. 
I switched back to my own async wrapper around process to cover this case, as suggested.

**Comment by EamonNerbonne** [comment]
@jamesmanning At work we have a wrapper quite similar to this one (I got involved here because I hoped to use this library rather than our own code in the first place), which as an api returns an object such as this one:

```C#
    public sealed class AsyncProcessResult {
        Task<int> ExitCode;
        public IObservable<(ProcessOutputKind Kind, string Line, TimeSpan OutputMoment)> Output;
        public void WriteToConsoleWithPrefix(string prefix); //interactively
        public Task<string> StdOutput();
        public Task<string> StdError();
    }
```

It's been battle tested and deals with a number of consequences and API gotchas (e.g. such as that `BeginErrorReadLine` can fail and there's nothing you can do about it).  The output stream is both live and cached; so a listener never misses any process output even when the start listening a little later, and it retains the interleaving of stderr and stdout, which can be useful when calling tools that write to both streams in a specific order.

Would you be interesting in including something like that here?  Obviously, I'd need a green light from my employer, but hey, I can always try.

Downside would be a dependency on RX; but frankely you kind of want that for this kind of thing.  If you think that (or the complexity) is too high a price I can see if it's otherwise publically redistributable.

**Comment by dazinator** [comment]
@EamonNerbonne

I ended up writing a very simple implementation like this:

```

    public class ProcessAsync : IDisposable
    {
        private Process _process;      

        public Task<int> RunAsync(ProcessStartInfo processStartInfo, Action<string> onDataReceived = null, Action<string> onErrorReceived = null)
        {
            var tcs = new TaskCompletionSource<int>();
            var p = _process = new Process();

            p.StartInfo = processStartInfo;
            p.EnableRaisingEvents = true;
            p.OutputDataReceived += (s, e) =>
            {
                onDataReceived?.Invoke(e.Data);             
            };

            p.ErrorDataReceived += (s, e) =>
            {
                onErrorReceived?.Invoke(e.Data);             
            };

            p.Start();
            p.BeginOutputReadLine();
            p.Exited += (s, e) =>
            {
                tcs.SetResult(p.ExitCode);              
            };

            return tcs.Task;
        }

        #region IDisposable Support
        private bool _disposedValue = false; // To detect redundant calls

        protected virtual void Dispose(bool disposing)
        {
            if (!_disposedValue)
            {
                if (disposing)
                {
                    // TODO: dispose managed state (managed objects).
                    _process.Dispose();
                    _process = null;
                }

                // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                // TODO: set large fields to null.
                _disposedValue = true;
            }
        }    

        // This code added to correctly implement the disposable pattern.
        public void Dispose()
        {
            // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
            Dispose(true);          
        }
        #endregion
    }

```

I am not actually interested in error out, just stdout and the exit code. I don't call `BeginErrorReadLine` so I am assuming I wouldn't get error out in the current implementation anyway? 
It sounds like from what you are saying I could hit issues with this implementation down the road in which case I would be very interested in using something more battle hardened if you are able to share.

**Comment by EamonNerbonne** [comment]
Sure, you could do various things in a layer higher up.  But that's partially also because this implementation does almost nothing; you cannot (e.g.) have both the simplicity of a "collect all output" and live reporting, for instance.  So e.g. process exit, OutputDataReceived, ErrorDataReceived are in an unavoidable race and additionally might be called concurrently.  Valid implementations of these event handlers aren't trivial if you want more than one.

**Comment by dazinator** [comment]
> So e.g. process exit, OutputDataReceived, ErrorDataReceived are in an unavoidable race and additionally might be called concurrently.

Would you be able to elaborate any further (or point me to anything about specifically the race?). I managed to find a few things about using `waitforexit` with a timeout being problematic (which is why I am not using any timeout.) but I m now wondering if there is something else I have missed?

>  But that's partially also because this implementation does almost nothing

It does the bare basics, in order to cover use cases where "collect all output" penalises in terms of unnecessary memory usage:-

- Awaiting an exit code only
- Awaiting an exit code, and reporting on stdout.

I suspect when I do need to collect the output, I'll wrap this, and my handlers will add the messages to a concurrent collection of some kind. I'll either inspect that after the process exits, or I'll make it observable. Or you will have managed to get permission to share your implementation in which case I will seriously consider using that :-)

**Comment by EamonNerbonne** [comment]
Standard error are standard input are really old concepts; they're implemented as streams now.  Although it's possible for streams to act in a synchronous fashoin, it's not typical.  Specifically, the `Process` streams are buffered (and even if they weren't, given the other layers here I wouln't rely on blocking semantics).  That means that if a sender sends A to stderr then B to stdout, you might receive the B first.

Not just that, the OutputDataReceived calls are called by an internal class [AsyncStreamReader](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs), and that simply uses Task.Run to start a background thread.  Notable: EACH stream reader has its own thread, and those are in totally separate, mutually unsynchronized threads.  So not only is there a race condition; the events are threaded and if you deal with em both you''re responsible for thread safety. 

And then there's the fact that process exit is yet another thread-unsafe concurrent event.  You can receive this and then still receive output.  Not *too* bad, except really confusing - but a lot of this stuff is IDisposable, and it would be nice to release all these I/O handles in a timely fashion.  But doing that when disposable is only legal after all events on various threads have fired is again a gotcha (and I really encountered this; it's not that hard to trigger).

Some of the least excusable bits are that `BeginOutputReadLine` is intrinsically in a race with process exit.  It is not legal to call BeginOutputReadLine before process start, but if your process is very fast (again, I really observed this), then you really can cause a crash when you call BeginOutputReadLine right after process start (and if you do, did you dispose?).

Frankly: the .net API here is utter garbage.  It's very unlikely even 1% of users are using it correctly. And it's not like it's somehow "raw" or efficient - just look at [the implementation](https://github.com/dotnet/corefx/tree/master/src/System.Diagnostics.Process/src/System/Diagnostics)!

**Comment by dazinator** [comment]
Thanks for the knowledge share and insights. I must admit I hadn't looked at the implementation. I had suspected buffers but as I dont care about preserving ordering (interleaving isnt something I do) this didnt seem a problem (for the present). However I can certainly see that being an issue if you do care! Also the process exiting before the call to begin reading the stream causes a crash? Seriously.. that is garbage. I can see what you mean about this being a can of worms for the unwary! 

So basically if you want to interleave / preserve the actual ordering I assume you need your own stream readers? Is this what your implementation involves i.e bypassing the events and reading from the underlying streams directly? 

I am aware of the concurrent nature of those events. This aspect didn't seem too bad to handle as long as you are aware of thread safety. I am a bit concerned though that an event might be raised after the exited event - is that a thing? That might be a problem for me if the exited event is raised and then later data / error received event occurs.. this is because I complete the await once the exited event occurs and I assume all output at that point has been processed.. it is important to me that I dont miss output :-)

**Comment by EamonNerbonne** [comment]
It's definitely a thing; it's easy to reproduce too: just start a process that makes a *LOT* of output, then exits.  I suspect simply `copy <huge-text-file> CON` will do.

**Comment by Daniel15** [comment]
> Would you be interesting in including something like that here? Obviously, I'd need a green light from my employer, but hey, I can always try.

@EamonNerbonne  - Did you end up posting this anywhere? I'd be interested in seeing it, even if you just post the code as a Gist with no support 😃

**Comment by EamonNerbonne** [comment]
https://github.com/progressonderwijs/ProgressOnderwijsUtils/blob/master/src/ProgressOnderwijsUtils/ProcessRunner.cs is the code (well, most of it)

Use examples you might derive from the tests: https://github.com/progressonderwijs/ProgressOnderwijsUtils/blob/master/test/ProgressOnderwijsUtils.Tests/ProcessRunnerTest.cs

There is a nuget package, but it's likely too large for what you want: https://www.nuget.org/packages/ProgressOnderwijsUtils/, since it's a kitchen sink collector for random utils extracted from internal projects; we don't bother splitting it because there's no clear point in doing so.

We could split that code off into a separate lib, or include it here, if there were actual motivation to do that.

**Comment by dazinator** [comment]
@EamonNerbonne 
I see the key to making it work is this line: https://github.com/progressonderwijs/ProgressOnderwijsUtils/blob/master/src/ProgressOnderwijsUtils/ProcessRunner.cs#L137

The power of venting :-)

**Comment by EamonNerbonne** [comment]
Guilty as charged ;-).

**Comment by EamonNerbonne** [comment]
@jamesmanning would you be interested in merging something like that into this package?  Downsides would be maintenance, the fact that there are 2 ways to start processes at all in one lib, and a dependency on RX. Upside would be that the package would cover more ways of practically running processes from .net core; because it's pretty hard to actually use the process api directly correctly.

Another alternative would be the new IAsyncEnumerable; haven't tried that, so I can't speak from experience.

**Comment by jamesmanning** [comment]
@EamonNerbonne TBH I'd rather keep this project focused on just the case where you want to fire off the process and then get the results when it's done.  Once you start down the path of trying to interact with it while it's running, I think you're better off either using Process directly or something like your ProgressOnderwijsUtils.

That's not to say there isn't value in supporting stdout/stderr as observables, just that I feel like it's still out of scope for the use case this is meant to cover of "go run this thing, report results back after it finishes" 🤷‍♂ Admittedly, that's why I closed this issue in the first place. 😄
