### ISSUE TITLE
Dispose of of the Process object

### ISSUE THREAD

**Issue by sindilevich** [jamesmanning/RunProcessAsTask#2]
Since `Process` implements `IDisposable`, it can be a good choice to dispose of of a `Process` object, after setting the `TaskCompletionSource` during the `Exited` event. It can be done by calling the `Process.Close()` method. Probably, there is a need copying all the relevant `Process` properties over to `ProcessResult` instance beforehand. Since calling `Process.Close()` will nullify them.

**Comment by jamesmanning** [comment]
It's an interesting question.  

I had initially decided against disposing it specifically because of all the information you lose when you do the Dispose/Close call. You can't copy everything from it, since you're going to lose the handle to the process (and to its main window if it has one) - copying the handle wouldn't matter since it'll be invalid once Close is called (and it calls m_processHandle.Close()).  By having it exposed on the ProcessResult object, for callers that want/need to have it disposed (they're in a long-running process/appdomain and want/need to have those particular resources freed up ), they're free to do so themselves.

Now, I *could* make ProcessResults implement IDisposable to help make it clear that there are native resources being held, and then its implementation could call Dispose on the Process instance that it's holding.  Does that seem like a reasonable approach?  Then I don't have to worry about prematurely disposing the process when the caller still wants a handle to it.  Does that sound ok?

Thanks, @sindilevich !

**Comment by sindilevich** [comment]
I didn't think of a need to obtain the `Handle` upon process exit, but it now make a good sense to me.

Your suggested approach, implementing the `IDisposable` interface on `ProcessResult` sounds very attractive. Not only it encapsulates freeing up the `Process` object by calling `Process.Dispose()`, it also declares intention.

Would be happy start using the code, once you implement the change and publish it on NuGet.

Thanks a lot!

**Comment by jamesmanning** [comment]
@sindilevich now on NuGet as version 1.1.2

Commit is https://github.com/jamesmanning/RunProcessAsTask/commit/7dda1d8c231452cd2eb282a115576f54317c7e53

Thanks!
